import React from 'react'

const Home=()=>{
    return(
        <>
        <h1><center>Home</center></h1>
    <div className="row">
        <div className="midside">
            <img src="welcomeImage.jpg" alt="welcome here"/>
        </div>
        <div className="rightside">
            <p>Our website is made using React.js, which is a Front-end Framework,which is very useful to make single page web applications.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel enim vel libero euismod lacinia. Phasellus eget mi ac est pellentesque mattis. Mauris semper gravida justo ut iaculis. Ut quis leo purus. Pellentesque vulputate, ipsum quis mollis volutpat, mauris arcu accumsan est, eget gravida dui enim vel nisl. In mattis, libero vitae pharetra gravida, libero lectus consequat mauris, eget bibendum felis nulla sed arcu. Suspendisse interdum scelerisque massa, eu interdum metus accumsan sit amet. Etiam vitae diam rutrum tortor volutpat rutrum. Integer at orci enim. Cras sit amet massa purus. Aenean at vehicula felis. Phasellus a tempus est. Mauris tristique risus quis maximus laoreet. Ut dignissim lorem volutpat risus iaculis lobortis. Ut varius id arcu eu egestas. Praesent ornare iaculis volutpat.
            Maecenas vestibulum semper nunc eget aliquet. Nullam semper convallis nulla. Nulla vitae metus sem. Ut in massa eros. Sed at diam et quam congue lobortis. Suspendisse rutrum porttitor cursus. Nulla ac convallis enim. Ut et interdum ligula. Nulla placerat ac nisi vitae posuere.            Suspendisse vestibulum lacus neque, a congue sapien finibus quis. Donec suscipit vel lorem porttitor laoreet. Morbi et congue leo. Fusce facilisis mollis augue, vitae porta mauris dignissim sit amet. Aenean mollis sed leo a accumsan. Morbi erat mauris, accumsan vitae tempus et, egestas quis ligula. Aenean nulla massa, lobortis mattis risus vel, vehicula tempor mi. </p>  
        </div>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. consectetur adipiscing elit. Nunc ac odio molestie, blandit tortor quis, suscipit sem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel enim vel libero euismod lacinia. Phasellus eget mi ac est pellentesque mattis. Mauris semper gravida justo ut iaculis. Ut quis leo purus. Pellentesque vulputate, ipsum quis mollis volutpat, mauris arcu accumsan est, eget gravida dui enim vel nisl. In mattis, libero vitae pharetra gravida, libero lectus consequat mauris, eget bibendum felis nulla sed arcu. Suspendisse interdum scelerisque massa, eu interdum metus accumsan sit amet. Etiam vitae diam rutrum tortor volutpat rutrum. Integer at orci enim. Cras sit amet massa purus. Aenean at vehicula felis. Phasellus a tempus est. Mauris tristique risus quis maximus laoreet. Ut dignissim lorem volutpat risus iaculis lobortis. Ut varius id arcu eu egestas. Praesent ornare iaculis volutpat.
            Maecenas vestibulum semper nunc eget aliquet. Nullam semper convallis nulla. Nulla vitae metus sem. Ut in massa eros. Sed at diam et quam congue lobortis. Suspendisse rutrum porttitor cursus. Nulla ac convallis enim. Ut et interdum ligula. Nulla placerat ac nisi vitae posuere.            Suspendisse vestibulum lacus neque, a congue sapien finibus quis. Donec suscipit vel lorem porttitor laoreet. Morbi et congue leo. Fusce facilisis mollis augue, vitae porta mauris dignissim sit amet. Aenean mollis sed leo a accumsan. Morbi erat mauris, accumsan vitae tempus et, egestas quis ligula. Aenean nulla massa, lobortis mattis risus vel, vehicula tempor mi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel enim vel libero euismod lacinia. Phasellus eget mi ac est pellentesque mattis. Mauris semper gravida justo ut iaculis. Ut quis leo purus. Pellentesque vulputate, ipsum quis mollis volutpat, mauris arcu accumsan est, eget gravida dui enim vel nisl. In mattis, libero vitae pharetra gravida, libero lectus consequat mauris, eget bibendum felis nulla sed arcu. Suspendisse interdum scelerisque massa, eu interdum metus accumsan sit amet. Etiam vitae diam rutrum tortor volutpat rutrum. Integer at orci enim. Cras sit amet massa purus. Aenean at vehicula felis. Phasellus a tempus est. Mauris tristique risus quis maximus laoreet. Ut dignissim lorem volutpat risus iaculis lobortis. Ut varius id arcu eu egestas. Praesent ornare iaculis volutpat.
            Maecenas vestibulum semper nunc eget aliquet. Nullam semper convallis nulla. Nulla vitae metus sem. Ut in massa eros. Sed at diam et quam congue lobortis. Suspendisse rutrum porttitor cursus. Nulla ac convallis enim. Ut et interdum ligula. Nulla placerat ac nisi vitae posuere.            Suspendisse vestibulum lacus neque, a congue sapien finibus quis. Donec suscipit vel lorem porttitor laoreet. Morbi et congue leo. Fusce facilisis mollis augue, vitae porta mauris dignissim sit amet. Aenean mollis sed leo a accumsan. Morbi erat mauris, accumsan vitae tempus et, egestas quis ligula. Aenean nulla massa, lobortis mattis risus vel, vehicula tempor mi.  </p>
        </>
    )
}
export default Home